package com.seal.hackathon.domain.enums;

public enum AuditAction {
    ACCOUNT_REGISTER,
    ACCOUNT_APPROVE,
    ACCOUNT_REJECT,
    GUEST_JUDGE_CREATE,
    SCORE_CREATE,
    SCORE_UPDATE,
    SCORE_FINALIZE,
    TEAM_DISQUALIFY,
    SUBMISSION_DISQUALIFY,
    JUDGE_ASSIGN,
    MENTOR_ASSIGN,
    RANKING_COMPUTE,
    PROMOTION_COMPUTE,
    PRIZE_AWARD,
    RESULT_PUBLISH,
    MENTOR_MESSAGE_SEND,
    VOTE_CAST
}
